In [1]:
import numpy as np

In [2]:
parameters = {'W1': np.array([[-0.00416758, -0.00056267],
        [-0.02136196,  0.01640271],
        [-0.01793436, -0.00841747],
        [ 0.00502881, -0.01245288]]),
 'W2': np.array([[-0.01057952, -0.00909008,  0.00551454,  0.02292208]]),
 'b1': np.array([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.]]),
 'b2': np.array([[ 0.]])}

In [3]:
cache = {'A1': np.array([[-0.00616578,  0.0020626 ,  0.00349619],
        [-0.05225116,  0.02725659, -0.02646251],
        [-0.02009721,  0.0036869 ,  0.02883756],
        [ 0.02152675, -0.01385234,  0.02599885]]),
 'A2': np.array([[ 0.5002307 ,  0.49985831,  0.50023963]]),
 'Z1': np.array([[-0.00616586,  0.0020626 ,  0.0034962 ],
        [-0.05229879,  0.02726335, -0.02646869],
        [-0.02009991,  0.00368692,  0.02884556],
        [ 0.02153007, -0.01385322,  0.02600471]]),
 'Z2': np.array([[ 0.00092281, -0.00056678,  0.00095853]])}

In [5]:
X = np.array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ]])

In [7]:
Y = np.array([[ True, False,  True]], dtype=bool)

In [21]:
m = X.shape[1]
m

3

In [8]:
# Backward propagation for a single hidden layer neural network

In [9]:
W1, W2 = parameters.get('W1'), parameters.get('W2')

In [11]:
W1.shape

(4, 2)

In [12]:
W2.shape

(1, 4)

In [13]:
A1, A2 = cache.get('A1'), cache.get('A2')

In [15]:
A1.shape

(4, 3)

In [16]:
A2.shape

(1, 3)

![](https://i.ibb.co/3h2mD68/Screenshot-from-2019-04-27-10-46-03.png)

In [17]:
# Gradients for backpropagation

In [18]:
dZ2 = A2 - Y
dZ2

array([[-0.4997693 ,  0.49985831, -0.49976037]])

In [23]:
print(dZ2.shape)
print(A1.shape)

(1, 3)
(4, 3)


In [22]:
dW2 = np.dot(dZ2, A1.T) / m
dW2

array([[ 0.00078841,  0.01765429, -0.00084166, -0.01022527]])

In [25]:
# axis=1 implies summing horizontally row wise
db2 = np.sum(dZ2, axis=1, keepdims=True) / m
db2

array([[-0.16655712]])

![](https://i.ibb.co/3fPS0Rz/Screenshot-from-2019-04-27-10-52-49.png)

In [26]:
# For dZ1, we first need to calculate gradient of g1Z1
grad_g1Z1 = 1 - np.power(A1, 2)
grad_g1Z1.shape

(4, 3)

In [27]:
dZ1 = np.dot(W2.T, dZ2) * grad_g1Z1
dZ1.shape

(4, 3)

In [28]:
dW1 = np.dot(dZ1, X.T) / m
dW1.shape

(4, 2)

In [29]:
db1 = np.sum(dZ1, axis=1, keepdims=True) / m
db1.shape

(4, 1)

# Logistic Regression Forward Propagation and Loss

In [1]:
import numpy as np

In [8]:
def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    z -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + np.exp(-1 * z))
    ### END CODE HERE ###
    
    return s

In [2]:
w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])

In [4]:
print(f'Shape of w: {w.shape}')
print(f'Shape of b: {1}')
print(f'Shape of X: {X.shape}')
print(f'Shape of Y: {Y.shape}')

Shape of w: (2, 1)
Shape of b: 1
Shape of X: (2, 3)
Shape of Y: (1, 3)


In [7]:
X

array([[ 1. ,  2. , -1. ],
       [ 3. ,  4. , -3.2]])

In [6]:
m = X.shape[1]
m

3

In [9]:
# Model output
A = sigmoid(np.dot(w.T, X) + b)
A

array([[0.99987661, 0.99999386, 0.00449627]])

In [17]:
cost = -np.mean(Y * np.log(A) + (1 - Y) * np.log(1 - A))
cost

5.801545319394553

# Backward propagation to find grads

In [18]:
dz = A - Y
dz

array([[-1.23394576e-04,  9.99993856e-01, -9.95503727e-01]])

In [25]:
dw = 1/m * np.dot(X, dz.T)
dw

array([[0.99845601],
       [2.39507239]])

In [28]:
db = 1/m * np.sum(dz)
db

0.001455578136784208

# Optimization